--- #YAML:1.0
name:                Mojo
version:             0.3
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    Cwd:                           0
    Digest::MD5:                   0
    Encode:                        0
    File::Basename:                0
    File::Path:                    0
    File::Spec:                    0
    File::Spec::Functions:         0
    File::Temp:                    0
    FindBin:                       0
    IO::File:                      0
    IO::Select:                    0
    IO::Socket:                    0
    MIME::Base64:                  0
    MIME::QuotedPrint:             0
    POSIX:                         0
    Test::Builder::Module:         0
    Test::Harness:                 0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
