# Copyright (C) 2008, Sebastian Riedel.

=head1 Getting Started

This was supposed to be written as part of a Perl Foundation grant,
sadly the Perl Foundation didn't have the money to sponsor it.

=head2 Your first application

*** These are just a few pointers in the right direction in case someone is
insane enough to beta test Mojo. :) ***

Use the application generator to create all neccessary files.

    mojo generate application MyFirstApp

Thats it, you have just created your very first Mojo application.
Now it's time to start the built in server.

    cd my_first_app
    bin/mojo daemon

You can visit your application at http://127.0.0.1:3000.
Testing is just as simple.

    bin/mojo test

There are many more helpful scripts, and mojo will list them for you.

    bin/mojo

Have fun!

=cut